# Generated by Django 3.1.4 on 2022-02-08 12:21

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('empid', models.IntegerField(primary_key=sqlalchemy.sql.expression.true, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='empdetails',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='appemployee.employee')),
                ('id', models.IntegerField(primary_key=sqlalchemy.sql.expression.true, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('grosssalary', models.CharField(max_length=100)),
            ],
            bases=('appemployee.employee',),
        ),
    ]
