# Generated by Django 3.1.4 on 2022-02-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appemployee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='empdetails',
            name='employee_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appemployee.employee'),
        ),
    ]
